module.exports = { headerAppText: 'Play sample application — Computer database',
                   placeholderFilterInput: 'Filter by computer name...',
                   valueFilterButton: 'Filter by name',
                   addNewComputerButtonText: 'Add a new computer',
                   tableHeaderComputer: 'Computer name',
                   tableHeaderIntroduced: 'Introduced',
                   tableHeaderDiscontinued: 'Discontinued',
                   tableHeaderCompany: 'Company',
                   nextButtonText: 'Next →',
                   previousButtonText: '← Previous',
                   formLabelComputer: 'Computer name',
                   formLabelIntroduced: 'Introduced date',
                   formLabelDiscontinued: 'Discontinued date',
                   formLabelCompany: 'Company',
                   headerAddComputerPage: "Add a computer",
                   computerName: 'Very Old Computer',
                   introducedDateStart: '1990-07-06',
                   discontinuedDateStart: '2016-07-06',
                   companyNumber: 17,
                   introducedDateEnd: '06 Jul 1990',
                   discontinuedDateEnd: '06 Jul 2016',
                   companyName: 'Sony',
                   inputNameComputer: 'name',
                   inputNameIntroduced: 'introduced',
                   inputNameDiscontinued: 'discontinued',
                   helpInlineComputer: 'Required',
                   helpInlineIntroduced: "Date ('yyyy-MM-dd')",
                   helpInlineDiscontinued: "Date ('yyyy-MM-dd')",
                   companySelectBoxText: '-- Choose a company --',
                   createComputerText: 'Create this computer'
                 };